author = Riccardo "Jack" Lucchetti and Artur Tarassow
email = atecon@posteo.de
version = 0.9
date = 2020-12-08
description = Retrieve metadata from gdt files.
tags = C81
min-version = 2020e
data-requirement = no-data-ok
public = get_metadata print_metadata
help = metadata_help.txt
sample-script = metadata_sample.inp
