author = Riccardo "Jack" Lucchetti and Artur Tarassow
email = atecon@posteo.de
version = 0.9
date = 2020-12-06
description = Retrieve metadata from gdt files.
tags = C13 C52
min-version = 20205
public = get_metadata print_metadata
help = metadata_help.txt
sample-script = metadata_sample.inp
